### PR TITLE
Update security.md

### PR DESCRIPTION
**Pull request by Aaron-Junker**
Related to microsoft/.github#62

### CODE REVIEW

**Comment by jeffwilcox** [comment]
Aaron I just wanted to say thanks for hanging with us on this.

One thing that we were aware of in the past was the pending GitHub security reporting features that allow people to submit requests to repository admins to handle. We're still having internal discussions about whether that path is suggested, to keep things GitHub-native, or if the current process of working through the official MSRC process is best.

I think this is a case where the official process might be best, but we have to have a plan for the other aspect as well. So that's a bit of why we're paused.

**Comment by to8824gold** [comment]
ありがとう

**Comment by Bossesoneroom** [comment]
Thank  you litle by litle i undertand

**Comment by Bossesoneroom** [comment]
How to commen

**Review by FBoucher — APPROVED** [review]
LGTM 👍

**Comment by Aaron-Junker** [comment]
@jeffwilcox Any updates with your internal discussions?

**Review by jeffwilcox — APPROVED** [review]

**Comment by jeffwilcox** [comment]
Let's ship it!

**Comment by Aaron-Junker** [comment]
@jeffwilcox Can you then merge https://github.com/microsoft/.github/pull/62 too?

**Pull request merged**
